add Omega branch
xbmc/repo-resources pull request #352
Opened 2023-02-19 04:41 UTC by fuzzard

@gade01 can you just confirm the yml file is correct

2023-02-19 11:14 UTC, gade01 approved these changes
@fuzzard It looks great, thanks.

2023-02-19 11:25 UTC, enen92 requested changes
Addon checker job is missing on omega (btw, also missing in nexus).
File in matrix: https://github.com/xbmc/repo-resources/blob/matrix/.github/workflows/addon-checker.yml

2023-02-20 03:49 UTC, fuzzard commented
Added addon-checker.yml

2023-02-20 03:52 UTC, garbear commented on README.md
> +Your add-on must follow our strict repository rules to be considered for inclusion. Please consult the [Add-on rules] (http://kodi.wiki/view/Add-on_Rules) wiki page for further details. Please review
Spelling: carefull -> carefully

2023-02-20 03:53 UTC, garbear commented on README.md
> +After you have read the repository guidelines and made sure your addon is compliant with them, you may begin the submission process. By forking this repository and creating a pull-request to the corr
grammar: "included you add-on to" -> "include your add-on in".

grammar: "send" -> "sending"

2023-02-20 03:54 UTC, garbear commented on README.md
> +This branch is used for add-ons that are coded for Kodi v21 Omega builds and higher only. From these code repositories and branches our back-end uploades .zip files of the compatible add-ons to our m
Spelling: "uploades" -> "uploads"

2023-02-20 03:55 UTC, garbear commented on README.md
> +The contents of this repository mainly consist of add-on created by third party developers. Team Kodi holds no responsibility for it's contents.
Grammar: "add-on" -> "add-ons"

Grammer: "it's" -> "its"

2023-02-20 08:32 UTC, enen92 approved these changes

2023-02-20 08:32 UTC, merged