resource.fonts.copacetic 1.0.0
xbmc/repo-resources pull request #392
Opened 2023-04-17 10:01 UTC by realcopacetic

Initial repo submission for resource.fonts.copacetic

### Description
A new resource dependency for the skin Copacetic, submitted to rep-skins repo. This resource provides additional font support, a typeset combining Inter for latin characters with Noto Sans for CJK.

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

2023-04-30 09:43 UTC, romanvm approved these changes

2023-04-30 09:46 UTC, romanvm requested changes
Please fix errors found by the addon checker

2023-04-30 10:14 UTC, pkscout approved these changes

2023-04-30 16:59 UTC, realcopacetic commented
hello @romanvm apologies for the errors. I think I have fixed them all. Regards,
Ash

2023-05-01 08:11 UTC, realcopacetic commented
Sorry @romanvm can you shed any light on these 2 errors as I don't understand them?

> ERROR: kodi.resource.font is not a valid extension point

I thought this was a valid extension point as listed here: https://kodi.wiki/view/Addon.xml
Have I used it incorrectly?

> ERROR: Schema validation failed for root addon element

I'm not sure where I've gone wrong with the schema. Is this related to the error above?

2023-05-01 08:46 UTC, romanvm commented
I'll check this. The extension point should be valid.

2023-05-01 19:38 UTC, realcopacetic commented
> I'll check this. The extension point should be valid.

Thanks!

2023-05-02 08:59 UTC, romanvm commented
Please also fix the fanart size.

2023-05-02 10:07 UTC, realcopacetic commented
> Please also fix the fanart size.

Done and squashed commits

2023-05-08 19:47 UTC, romanvm commented
LGTM but addon checker needs to be fixed.

2023-05-08 19:47 UTC, romanvm approved these changes

2023-05-09 10:16 UTC, realcopacetic commented
Thanks @romanvm do you know the expected time frame for that? I'm wondering whether it's better to remove this as a dependency from my skin so it will at least work for most people in the official repo without added CJK language support.

2023-05-09 22:02 UTC, romanvm commented
I cannot really tell when the checker will be fixed. So if this font package is not critical for your skin it's better to skip it for now. I'd merge it if I could but this repo is configured in such way that green checker run is mandatory.

2023-05-13 09:54 UTC, enen92 commented
@realcopacetic I took some time to update addon-checker and adding support for font addons in the PR above.
You're addon xml is wrong though:

```
INFO: This is a new addon
failed validating {'point': 'kodi.resource.font', 'compile': 'false'} with XsdAttributeGroup(['point']):

Reason: 'compile' attribute not allowed for element

Schema:

  <xs:complexType xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:attribute name="point" type="simpleIdentifier" use="required" />
  </xs:complexType>

Instance:

  <extension point="kodi.resource.font" compile="false" />
```

Please drop the `compile` attribute from the extension element, this is not valid according to the Kodi core code.

2023-05-13 09:55 UTC, enen92 commented on resource.fonts.copacetic/addon.xml
> +    <extension point="kodi.resource.font" compile="false" />
```suggestion
    <extension point="kodi.resource.font" />
```

2023-05-13 09:55 UTC, enen92 requested changes
After the addon.xml is fixed it can be merged

2023-05-13 15:55 UTC, realcopacetic commented
> After the addon.xml is fixed it can be merged

Ah great thanks @enen92 - I think I copied that compile bit from a different resource addon I found as I couldn't find much documentation, thanks for fixing. That's now updated.

2023-05-13 16:19 UTC, enen92 approved these changes

2023-05-13 16:19 UTC, merged

2023-05-13 16:20 UTC, enen92 commented
Great. If you find some issue with addon-checker feel free to ping me directly, I try to maintain it overtime (best effort ofc)